package com.huawei.clouds.openrewrite.bcprovjdk18on;

import org.openrewrite.ExecutionContext;
import org.openrewrite.Recipe;
import org.openrewrite.Tree;
import org.openrewrite.java.JavaIsoVisitor;
import org.openrewrite.java.tree.Expression;
import org.openrewrite.java.tree.J;
import org.openrewrite.java.tree.JavaType;
import org.openrewrite.java.tree.TypeUtils;
import org.openrewrite.marker.SearchResult;

import java.util.Locale;
import java.util.Set;

/** Locate compile and behavior boundaries established by the official 1.75 to 1.84 source diff. */
public final class FindBcProv184SourceRisks extends Recipe {
    static final String LEGACY_PQC_REMOVED =
            "Bouncy Castle 1.82 removed the old org.bouncycastle.pqc.legacy.crypto/math implementation; " +
            "select a standardized replacement, regenerate keys/test vectors, and plan persisted-key compatibility";
    static final String PQC_REMOVED =
            "This experimental PQC API/provider was removed or promoted on the path to 1.84; do not rename it " +
            "mechanically—choose ML-KEM/ML-DSA/SLH-DSA or another supported algorithm and validate encodings/vectors";
    static final String LEGACY_PQC_MOVED =
            "1.84 moved this non-standard BIKE, Picnic, or Rainbow lightweight API under pqc.legacy; " +
            "the package migration is automatic, but persisted keys, vectors, provider availability, and retirement must be reviewed";
    static final String SPHINCS_SEMANTICS =
            "SPHINCS+ cannot be package-renamed safely without the exact source version and parameter: 1.75 " +
            "unsuffixed names select robust variants, 1.78+ selects standardized simple variants, and 1.78/1.78.1 " +
            "cross-bind two SHA2 JCA parameter names; select the 1.84 legacy parameter from test vectors explicitly";
    static final String BCUTIL_SPLIT =
            "This ASN.1 type no longer ships in bcprov-jdk18on 1.84 and moved unchanged to bcutil-jdk18on; add an " +
            "owner-aligned org.bouncycastle:bcutil-jdk18on:1.84 dependency (the FQN remains the same)";
    static final String REMOVED_API =
            "This public bcprov API is absent or signature-incompatible in 1.84; use the documented replacement " +
            "and verify generated bytes rather than suppressing the compile failure";
    static final String PROVIDER =
            "Provider registration/order is process-global; 1.84 uses a newly RSA-signed provider JAR and changes " +
            "services over this upgrade span—verify duplicate BC/BCPQC providers, insertion order, class loaders, and startup policy";
    static final String ALGORITHM =
            "This BC/BCPQC algorithm name crosses experimental-to-standard or changed provider mappings; inventory " +
            "the resolved Provider.Service, parameter spec, key encoding, test vectors, and cross-version interoperability";
    static final String PKCS12 =
            "BC 1.84 changes PKCS12 provider behavior and enforces a default 5,000,000 iteration ceiling; verify " +
            "provider selection, aliases, passwords, iteration counts, stored output, HSM/custom-provider paths, and rollback";
    static final String ASN1 =
            "ASN.1 parsing/encoding is behavior-sensitive across 1.75-1.84 (OID validation plus 1.84 depth/size limits); " +
            "test malformed, deep, large, BER/DL/DER, canonical byte, signature, and persisted payload cases";
    static final String SERIALIZATION =
            "Java serialization of Bouncy Castle providers, composite keys, certificates, or implementation objects is " +
            "not a stable cross-version contract; replace it with a versioned standard encoding or test migration/rollback explicitly";
    static final String CRYPTO_PARAMETERS =
            "PQC parameter and private-key encodings changed across these releases; pin the standard/draft, " +
            "parameter set, context, seed/expanded form, expected secret length, and interoperability vectors";
    static final String STRINGS =
            "Strings.split was corrected in 1.84 for delimiters at position zero; verify callers that persisted or " +
            "interpreted the previous leading-delimiter result";
    static final String WRAP_UTIL =
            "WrapUtil moved packages and its key wrapping implementation changed across 1.75-1.84, including " +
            "no-KDF secret slicing; verify key-size handling, KDF output, wrapped bytes and cross-version unwrap vectors";

    private static final Set<String> BCUTIL_PACKAGES = Set.of(
            "org.bouncycastle.asn1.cryptlib.", "org.bouncycastle.asn1.edec.",
            "org.bouncycastle.asn1.gnu.", "org.bouncycastle.asn1.iana.",
            "org.bouncycastle.asn1.isara.", "org.bouncycastle.asn1.iso.",
            "org.bouncycastle.asn1.kisa.", "org.bouncycastle.asn1.microsoft.",
            "org.bouncycastle.asn1.misc.", "org.bouncycastle.asn1.mozilla.",
            "org.bouncycastle.asn1.nsri.", "org.bouncycastle.asn1.ntt.",
            "org.bouncycastle.asn1.oiw.", "org.bouncycastle.asn1.rosstandart.");
    private static final Set<String> REMOVED_TYPE_PREFIXES = Set.of(
            "org.bouncycastle.pqc.legacy.crypto.", "org.bouncycastle.pqc.legacy.math.",
            "org.bouncycastle.pqc.crypto.crystals.kyber.", "org.bouncycastle.pqc.crypto.gemss.",
            "org.bouncycastle.pqc.jcajce.provider.mceliece.");
    private static final Set<String> MOVED_LEGACY_PREFIXES = Set.of(
            "org.bouncycastle.pqc.crypto.bike.", "org.bouncycastle.pqc.crypto.picnic.",
            "org.bouncycastle.pqc.crypto.rainbow.",
            "org.bouncycastle.pqc.legacy.bike.", "org.bouncycastle.pqc.legacy.picnic.",
            "org.bouncycastle.pqc.legacy.rainbow.");
    private static final Set<String> REMOVED_TYPES = Set.of(
            "org.bouncycastle.jce.provider.BrokenKDF2BytesGenerator",
            "org.bouncycastle.asn1.util.Dump",
            "org.bouncycastle.pqc.jcajce.interfaces.QTESLAKey",
            "org.bouncycastle.pqc.jcajce.interfaces.RainbowKey",
            "org.bouncycastle.pqc.jcajce.interfaces.RainbowPrivateKey",
            "org.bouncycastle.pqc.jcajce.interfaces.RainbowPublicKey",
            "org.bouncycastle.pqc.jcajce.provider.McEliece",
            "org.bouncycastle.pqc.jcajce.provider.Rainbow",
            "org.bouncycastle.pqc.jcajce.spec.McElieceCCA2KeyGenParameterSpec",
            "org.bouncycastle.pqc.jcajce.spec.McElieceKeyGenParameterSpec",
            "org.bouncycastle.pqc.jcajce.spec.QTESLAParameterSpec",
            "org.bouncycastle.pqc.jcajce.spec.RainbowParameterSpec",
            "org.bouncycastle.pqc.asn1.GMSSPrivateKey",
            "org.bouncycastle.pqc.asn1.GMSSPublicKey",
            "org.bouncycastle.pqc.asn1.KyberPrivateKey",
            "org.bouncycastle.pqc.asn1.KyberPublicKey",
            "org.bouncycastle.pqc.asn1.McElieceCCA2PrivateKey",
            "org.bouncycastle.pqc.asn1.McElieceCCA2PublicKey",
            "org.bouncycastle.pqc.asn1.McEliecePrivateKey",
            "org.bouncycastle.pqc.asn1.McEliecePublicKey",
            "org.bouncycastle.pqc.asn1.RainbowPrivateKey",
            "org.bouncycastle.pqc.asn1.RainbowPublicKey");
    private static final Set<String> REMOVED_PUBLIC_TYPES = Set.of(
            "org.bouncycastle.pqc.crypto.lms.HSSSignature",
            "org.bouncycastle.pqc.crypto.lms.LMSException");
    private static final Set<String> BLOCK_SIZE_REMOVED = Set.of(
            "org.bouncycastle.crypto.engines.ElephantEngine",
            "org.bouncycastle.crypto.engines.ISAPEngine",
            "org.bouncycastle.crypto.engines.PhotonBeetleEngine",
            "org.bouncycastle.crypto.engines.XoodyakEngine");
    private static final Set<String> JCA_FACTORIES = Set.of(
            "java.security.AlgorithmParameterGenerator", "java.security.AlgorithmParameters",
            "java.security.KeyFactory", "java.security.KeyPairGenerator", "java.security.KeyStore",
            "java.security.MessageDigest", "java.security.SecureRandom", "java.security.Signature",
            "java.security.cert.CertificateFactory", "javax.crypto.Cipher", "javax.crypto.KeyAgreement",
            "javax.crypto.KeyGenerator", "javax.crypto.Mac", "javax.crypto.SecretKeyFactory");

    @Override
    public String getDisplayName() {
        return "Find Bouncy Castle Provider 1.84 source migration risks";
    }

    @Override
    public String getDescription() {
        return "Mark removed PQC and ASN.1 APIs, provider registration and algorithm lookup, PKCS12, DER/ASN.1, " +
               "serialization, and crypto-parameter boundaries that require application evidence.";
    }

    @Override
    public JavaIsoVisitor<ExecutionContext> getVisitor() {
        return new JavaIsoVisitor<ExecutionContext>() {
            @Override
            public J.CompilationUnit visitCompilationUnit(J.CompilationUnit cu, ExecutionContext ctx) {
                return UpgradeSelectedBcProvDependency.generated(cu.getSourcePath()) ? cu :
                        super.visitCompilationUnit(cu, ctx);
            }

            @Override
            public J.Import visitImport(J.Import anImport, ExecutionContext ctx) {
                J.Import visited = super.visitImport(anImport, ctx);
                String message = typeMessage(visited.getTypeName());
                return message == null ? visited : mark(visited, message);
            }

            @Override
            public J.Identifier visitIdentifier(J.Identifier identifier, ExecutionContext ctx) {
                J.Identifier visited = super.visitIdentifier(identifier, ctx);
                JavaType.Variable field = visited.getFieldType();
                if (field != null && visited.getSimpleName().endsWith("_aes") &&
                    "org.bouncycastle.pqc.crypto.crystals.dilithium.DilithiumParameters"
                            .equals(fqn(field.getOwner()))) return mark(visited, REMOVED_API);
                return visited;
            }

            @Override
            public J.NewClass visitNewClass(J.NewClass newClass, ExecutionContext ctx) {
                J.NewClass visited = super.visitNewClass(newClass, ctx);
                String type = fqn(visited.getType());
                String message = typeMessage(type);
                if (message != null) return mark(visited, message);
                if ("org.bouncycastle.asn1.ASN1InputStream".equals(type) ||
                    "org.bouncycastle.asn1.ASN1ObjectIdentifier".equals(type)) return mark(visited, ASN1);
                if ("org.bouncycastle.pqc.crypto.lms.LMSContext".equals(type)) return mark(visited, REMOVED_API);
                if ("org.bouncycastle.asn1.sec.ECPrivateKey".equals(type) && removedEcPrivateKeyConstructor(visited)) {
                    return mark(visited, REMOVED_API);
                }
                if (pqcParameterType(type)) {
                    return mark(visited, CRYPTO_PARAMETERS);
                }
                return visited;
            }

            @Override
            public J.MethodInvocation visitMethodInvocation(J.MethodInvocation invocation, ExecutionContext ctx) {
                J.MethodInvocation visited = super.visitMethodInvocation(invocation, ctx);
                JavaType.Method method = visited.getMethodType();
                String owner = method == null ? "" : fqn(method.getDeclaringType());
                String name = visited.getSimpleName();

                if ("getEncoded".equals(name) && pqcType(owner)) return mark(visited, CRYPTO_PARAMETERS);
                String typeRisk = typeMessage(owner);
                if (typeRisk != null) return mark(visited, typeRisk);
                if ("getBlockSize".equals(name) && BLOCK_SIZE_REMOVED.contains(owner) ||
                    "getParameters".equals(name) && "org.bouncycastle.asn1.sec.ECPrivateKey".equals(owner) ||
                    "getPublicKey".equals(name) && "org.bouncycastle.pqc.crypto.lms.LMSContext".equals(owner) ||
                    "generateKeyPairWithSeed".equals(name) &&
                    "org.bouncycastle.pqc.crypto.hqc.HQCKeyPairGenerator".equals(owner) ||
                    "extractGcmParameters".equals(name) &&
                    "org.bouncycastle.jcajce.provider.symmetric.util.GcmSpecUtil".equals(owner)) {
                    return mark(visited, REMOVED_API);
                }
                if ("split".equals(name) && "org.bouncycastle.util.Strings".equals(owner)) {
                    return mark(visited, STRINGS);
                }
                if (isProviderManagement(owner, name) && bcProviderArgument(visited)) return mark(visited, PROVIDER);
                if ("getProvider".equals(name) && "java.security.Security".equals(owner) &&
                    firstString(visited).map(FindBcProv184SourceRisks::bcProviderName).orElse(false)) {
                    return mark(visited, PROVIDER);
                }
                if ("getInstance".equals(name) && JCA_FACTORIES.contains(owner)) {
                    String algorithm = firstString(visited).orElse("");
                    boolean explicitBc = visited.getArguments().stream().skip(1)
                            .anyMatch(FindBcProv184SourceRisks::bcProviderExpression);
                    if ("java.security.KeyStore".equals(owner) && "PKCS12".equalsIgnoreCase(algorithm) && explicitBc) {
                        return mark(visited, PKCS12);
                    }
                    if (changedAlgorithm(algorithm) && (explicitBc || pqcAlgorithm(algorithm))) {
                        return mark(visited, ALGORITHM);
                    }
                }
                if ("writeObject".equals(name) && "java.io.ObjectOutputStream".equals(owner) &&
                    !visited.getArguments().isEmpty() && bouncyCastleType(visited.getArguments().get(0).getType())) {
                    return mark(visited, SERIALIZATION);
                }
                if ("fromByteArray".equals(name) && "org.bouncycastle.asn1.ASN1Primitive".equals(owner) ||
                    "getEncoded".equals(name) && owner.startsWith("org.bouncycastle.asn1.")) {
                    return mark(visited, ASN1);
                }
                return visited;
            }

            @Override
            public J.Literal visitLiteral(J.Literal literal, ExecutionContext ctx) {
                J.Literal visited = super.visitLiteral(literal, ctx);
                if (!(visited.getValue() instanceof String value)) return visited;
                String message = typeMessage(value);
                return message == null ? visited : mark(visited, message);
            }
        };
    }

    private static boolean removedEcPrivateKeyConstructor(J.NewClass newClass) {
        JavaType.Method constructor = newClass.getConstructorType();
        if (constructor == null || constructor.getParameterTypes().isEmpty()) return false;
        return TypeUtils.isOfClassType(constructor.getParameterTypes().get(0), "java.math.BigInteger");
    }

    private static boolean isProviderManagement(String owner, String name) {
        return "java.security.Security".equals(owner) &&
               Set.of("addProvider", "insertProviderAt", "removeProvider").contains(name);
    }

    private static boolean bcProviderArgument(J.MethodInvocation invocation) {
        return invocation.getArguments().stream().anyMatch(FindBcProv184SourceRisks::bcProviderExpression);
    }

    private static boolean bcProviderExpression(Expression expression) {
        if (expression instanceof J.Literal literal && literal.getValue() instanceof String value) {
            return bcProviderName(value);
        }
        String type = fqn(expression.getType());
        return "org.bouncycastle.jce.provider.BouncyCastleProvider".equals(type) ||
               "org.bouncycastle.pqc.jcajce.provider.BouncyCastlePQCProvider".equals(type);
    }

    private static boolean bcProviderName(String value) {
        return "BC".equalsIgnoreCase(value) || "BCPQC".equalsIgnoreCase(value);
    }

    private static java.util.Optional<String> firstString(J.MethodInvocation invocation) {
        if (invocation.getArguments().isEmpty() ||
            !(invocation.getArguments().get(0) instanceof J.Literal literal) ||
            !(literal.getValue() instanceof String value)) return java.util.Optional.empty();
        return java.util.Optional.of(value);
    }

    private static boolean changedAlgorithm(String algorithm) {
        String compact = algorithm.toUpperCase(Locale.ROOT).replaceAll("[^A-Z0-9]", "");
        return Set.of("KYBER", "DILITHIUM", "SPHINCS", "SPHINCSPLUS", "RAINBOW", "MCELIECE", "GMSS",
                      "QTESLA", "BIKE", "PICNIC", "FALCON", "HQC", "MLKEM", "MLDSA", "SLHDSA",
                      "DSTU4145").stream().anyMatch(compact::contains);
    }

    private static boolean pqcAlgorithm(String algorithm) {
        String compact = algorithm.toUpperCase(Locale.ROOT).replaceAll("[^A-Z0-9]", "");
        return Set.of("KYBER", "DILITHIUM", "SPHINCS", "RAINBOW", "MCELIECE", "GMSS", "QTESLA",
                      "BIKE", "PICNIC", "FALCON", "HQC", "MLKEM", "MLDSA", "SLHDSA")
                .stream().anyMatch(compact::contains);
    }

    private static String typeMessage(String type) {
        if (type == null || type.isEmpty()) return null;
        if ("org.bouncycastle.pqc.jcajce.provider.util.WrapUtil".equals(type) ||
            "org.bouncycastle.jcajce.provider.asymmetric.util.WrapUtil".equals(type)) return WRAP_UTIL;
        if (BCUTIL_PACKAGES.stream().anyMatch(type::startsWith)) return BCUTIL_SPLIT;
        if (REMOVED_PUBLIC_TYPES.contains(type)) return REMOVED_API;
        if (type.startsWith("org.bouncycastle.pqc.crypto.sphincsplus.") ||
            type.startsWith("org.bouncycastle.pqc.legacy.sphincsplus.")) return SPHINCS_SEMANTICS;
        if (type.startsWith("org.bouncycastle.pqc.legacy.crypto.") ||
            type.startsWith("org.bouncycastle.pqc.legacy.math.")) return LEGACY_PQC_REMOVED;
        if (REMOVED_TYPE_PREFIXES.stream().anyMatch(type::startsWith) || REMOVED_TYPES.contains(type)) return PQC_REMOVED;
        if (MOVED_LEGACY_PREFIXES.stream().anyMatch(type::startsWith)) return LEGACY_PQC_MOVED;
        return null;
    }

    private static boolean pqcParameterType(String type) {
        return pqcType(type) && (type.endsWith("Parameters") || type.endsWith("ParameterSpec") ||
                                 type.endsWith("PrivateKeyParameters") || type.endsWith("PublicKeyParameters"));
    }

    private static boolean pqcType(String type) {
        return type != null && type.startsWith("org.bouncycastle.pqc.");
    }

    private static boolean bouncyCastleType(JavaType type) {
        return fqn(type).startsWith("org.bouncycastle.");
    }

    private static String fqn(JavaType type) {
        JavaType.FullyQualified fullyQualified = TypeUtils.asFullyQualified(type);
        return fullyQualified == null ? "" : fullyQualified.getFullyQualifiedName();
    }

    private static <T extends Tree> T mark(T tree, String message) {
        return tree.getMarkers().findAll(SearchResult.class).stream()
                .anyMatch(result -> message.equals(result.getDescription()))
                ? tree : SearchResult.found(tree, message);
    }
}
