package com.huawei.clouds.openrewrite.ws;

import org.openrewrite.Cursor;
import org.openrewrite.ExecutionContext;
import org.openrewrite.Recipe;
import org.openrewrite.TreeVisitor;
import org.openrewrite.json.JsonIsoVisitor;
import org.openrewrite.json.tree.Json;
import org.openrewrite.marker.SearchResult;

import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** Marks package-manager, runtime, native-addon, typing, and browser ownership decisions. */
public final class FindWsManifestRisks extends Recipe {
    private static final Set<String> CENTRAL_OWNERS = Set.of("overrides", "resolutions", "pnpm", "catalog", "catalogs");
    private static final Pattern FIRST_NODE_VERSION = Pattern.compile("^(?:>=|>|\\^|~)?v?(\\d+)");

    @Override
    public String getDisplayName() {
        return "Find ws 8.21.0 manifest migration risks";
    }

    @Override
    public String getDescription() {
        return "Marks skipped ws declarations plus package-manager ownership, Node runtime, optional native addon, typings, and browser-bundling decisions.";
    }

    @Override
    public TreeVisitor<?, ExecutionContext> getVisitor() {
        return new JsonIsoVisitor<ExecutionContext>() {
            private boolean wsManifest;

            @Override
            public Json.Document visitDocument(Json.Document document, ExecutionContext ctx) {
                if (!WsSupport.isPackageJson(document.getSourcePath())) return document;
                boolean old = wsManifest;
                wsManifest = containsWs(document);
                Json.Document visited = super.visitDocument(document, ctx);
                wsManifest = old;
                return visited;
            }

            @Override
            public Json.Member visitMember(Json.Member member, ExecutionContext ctx) {
                Json.Member visited = super.visitMember(member, ctx);
                if (!wsManifest) return visited;
                String key = WsSupport.key(visited);
                String value = WsSupport.stringValue(visited);
                String section = WsSupport.directDependencySection(getCursor());
                if (WsSupport.PACKAGE.equals(key) && !section.isEmpty() && value != null &&
                    WsSupport.replacement(value) == null && !WsSupport.isTarget(value)) {
                    return mark(visited, "Strict migration skipped this complex range, protocol, alias, tag, or non-workbook ws version; choose a tested 8.21.0 constraint and regenerate the owning lockfile");
                }
                if (WsSupport.PACKAGE.equals(key) && hasCentralOwnerAncestor()) {
                    return mark(visited, "This override, resolution, pnpm policy, or catalog owns ws independently; reconcile it with 8.21.0 and regenerate the lockfile instead of editing generated bytes");
                }
                if ("node".equals(key) && "engines".equals(parentKey()) && value != null && belowNode10(value)) {
                    return mark(visited, "ws 8.21.0 requires Node >=10; align local, CI, container, Electron, build-agent, and production runtimes before rollout");
                }
                if (("bufferutil".equals(key) || "utf-8-validate".equals(key)) && !section.isEmpty()) {
                    return mark(visited, "Review this optional ws native addon against the deployed Node floor and supply-chain policy; ws supports WS_NO_BUFFER_UTIL/WS_NO_UTF_8_VALIDATE when untrusted resolution is a concern");
                }
                if ("@types/ws".equals(key) && !section.isEmpty()) {
                    return mark(visited, "ws ships JavaScript and relies on @types/ws for TypeScript declarations; align its major/API surface and run the actual compiler after the runtime upgrade");
                }
                if ("browser".equals(key)) {
                    return mark(visited, "ws is a Node WebSocket implementation and its browser export rejects use; verify browser bundles use the native WebSocket API or an intentional isomorphic adapter");
                }
                return visited;
            }

            private String parentKey() {
                Cursor object = getCursor().getParent();
                Cursor parent = object == null ? null : object.getParent();
                return parent != null && parent.getValue() instanceof Json.Member member ? WsSupport.key(member) : "";
            }

            private boolean hasCentralOwnerAncestor() {
                Cursor cursor = getCursor().getParent();
                while (cursor != null && !(cursor.getValue() instanceof Json.Document)) {
                    if (cursor.getValue() instanceof Json.Member ancestor && CENTRAL_OWNERS.contains(WsSupport.key(ancestor))) return true;
                    cursor = cursor.getParent();
                }
                return false;
            }

            private Json.Member mark(Json.Member member, String message) {
                return member.getValue() instanceof Json.Literal
                        ? member.withValue(SearchResult.found(member.getValue(), message))
                        : SearchResult.found(member, message);
            }
        };
    }

    private static boolean belowNode10(String declaration) {
        String value = declaration.replace(" ", "").toLowerCase();
        if (value.contains("||") || value.startsWith("<") && !value.startsWith(">=")) return true;
        Matcher matcher = FIRST_NODE_VERSION.matcher(value);
        return matcher.find() && Integer.parseInt(matcher.group(1)) < 10;
    }

    private static boolean containsWs(Json.Document document) {
        if (!(document.getValue() instanceof Json.JsonObject root)) return false;
        for (Json child : root.getMembers()) {
            if (!(child instanceof Json.Member section) ||
                !WsSupport.DEPENDENCY_SECTIONS.contains(WsSupport.key(section)) ||
                !(section.getValue() instanceof Json.JsonObject entries)) continue;
            for (Json entry : entries.getMembers()) {
                if (entry instanceof Json.Member member && WsSupport.PACKAGE.equals(WsSupport.key(member))) return true;
            }
        }
        return false;
    }
}
