package com.huawei.clouds.openrewrite.bootstrap;

import org.openrewrite.ExecutionContext;
import org.openrewrite.Recipe;
import org.openrewrite.Tree;
import org.openrewrite.TreeVisitor;
import org.openrewrite.marker.Markers;
import org.openrewrite.marker.SearchResult;
import org.openrewrite.text.PlainText;
import org.openrewrite.text.PlainTextVisitor;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** Marks exact Bootstrap Yarn and pnpm lockfile package keys. */
public final class FindBootstrapTextLockRisks extends Recipe {
    private static final Pattern ENTRY = Pattern.compile(
            "(?m)(?<![@/A-Za-z0-9_.-])bootstrap(?=@|:|/|\\s)");

    @Override
    public String getDisplayName() {
        return "Find Bootstrap Yarn and pnpm lockfile risks";
    }

    @Override
    public String getDescription() {
        return "Marks Bootstrap lock entries that must be regenerated by the repository's package manager.";
    }

    @Override
    public TreeVisitor<?, ExecutionContext> getVisitor() {
        return new PlainTextVisitor<ExecutionContext>() {
            @Override
            public PlainText visitText(PlainText text, ExecutionContext ctx) {
                PlainText visited = super.visitText(text, ctx);
                if (!BootstrapSupport.isLockfile(visited.getSourcePath())) return visited;
                String source = visited.getText();
                Matcher matcher = ENTRY.matcher(source);
                List<PlainText.Snippet> snippets = new ArrayList<>();
                int cursor = 0;
                while (matcher.find()) {
                    if (matcher.start() > cursor) snippets.add(new PlainText.Snippet(
                            Tree.randomId(), Markers.EMPTY, source.substring(cursor, matcher.start())));
                    snippets.add(SearchResult.found(new PlainText.Snippet(Tree.randomId(), Markers.EMPTY,
                                    matcher.group()),
                            "Regenerate this lockfile; versions, resolved artifacts, integrity, peer snapshots, and package-manager metadata must come from the owning package manager"));
                    cursor = matcher.end();
                }
                if (snippets.isEmpty()) return visited;
                if (cursor < source.length()) snippets.add(new PlainText.Snippet(
                        Tree.randomId(), Markers.EMPTY, source.substring(cursor)));
                return visited.withText("").withSnippets(snippets);
            }
        };
    }
}
