package com.huawei.clouds.openrewrite.bootstrap;

import org.openrewrite.ExecutionContext;
import org.openrewrite.Recipe;
import org.openrewrite.TreeVisitor;
import org.openrewrite.text.PlainText;
import org.openrewrite.text.PlainTextVisitor;

import java.util.List;

import static com.huawei.clouds.openrewrite.bootstrap.BootstrapPlainTextSupport.risk;

/** Marks structural template, accessibility, Sass, CSS, CDN, and copied-asset changes. */
public final class FindBootstrapTemplateStyleRisks extends Recipe {
    private static final List<BootstrapPlainTextSupport.Risk> MARKUP = List.of(
            risk("\\bdata-(?:toggle|target|dismiss|parent|ride|slide|slide-to|spy|offset|interval|keyboard|backdrop|placement|content|title|trigger|container|delay|html|sanitize|boundary|reference|display|touch|wrap|pause)\\s*=",
                    "This unconverted Bootstrap 3/4 data attribute needs a data-bs-* name only when Bootstrap owns the widget; verify component semantics, selectors, event timing, and accessibility"),
            risk("(?<![:\\w-])class(?:Name)?\\s*=\\s*(['\"])[^'\"]*(?:custom-control|custom-checkbox|custom-radio|custom-switch|custom-file|form-control-file|input-group-(?:append|prepend)|form-(?:group|row|inline)|control-label)(?:\\s|['\"])",
                    "Bootstrap 5 structurally redesigned forms and input groups; migrate container, input, label, feedback, validation, and accessibility markup as one component"),
            risk("(?<![:\\w-])class(?:Name)?\\s*=\\s*(['\"])[^'\"]*(?:glyphicon(?:-\\w+)?|panel(?:-\\w+)?|well|thumbnail|pull-(?:left|right)|navbar-default|btn-default)(?:\\s|['\"])",
                    "This Bootstrap 3 component or utility has no single Bootstrap 5 token equivalent; redesign the component and verify responsive layout and visual snapshots"),
            risk("(?<![:\\w-])class(?:Name)?\\s*=\\s*(['\"])[^'\"]*(?<![A-Za-z0-9_-])(?:badge-(?:primary|secondary|success|danger|warning|info|light|dark)|close|thead-(?:light|dark)|text-(?:justify|hide)|pre-scrollable|rounded-(?:sm|lg)|btn-block)(?:\\s|['\"])",
                    "This removed Bootstrap 4 class requires a contextual replacement; verify contrast, close-button content, table scope, responsive sizing, focus, and application CSS"),
            risk("(?<![:\\w-])class(?:Name)?\\s*=\\s*(['\"])[^'\"]*(?:m[lr](?:-(?:sm|md|lg|xl))?-n[1-5])(?:\\s|['\"])",
                    "Bootstrap 5 disables negative margins by default; choose an enabled negative utility, grid/gutter solution, or application-owned layout and test RTL"),
            risk("<[^>]*class\\s*=\\s*(['\"])[^'\"]*progress-bar[^'\"]*\\1[^>]*role\\s*=\\s*(['\"])progressbar\\2[^>]*>",
                    "Bootstrap 5.3 moves progressbar role and aria value attributes to the outer .progress element; update the accessible structure and test screen-reader output"),
            risk("(?:https?:)?//[^\"'\\s>]+/bootstrap(?:@[^/\"'\\s]+)?/dist/(?:css|js)/[^\"'\\s>]+",
                    "This Bootstrap CDN asset needs a 5.3.6 filename plus matching SRI, crossorigin, CSP, cache, bundle/Popper choice, and fallback review"),
            risk("(?:vendor|node_modules)/bootstrap/(?:dist|js|scss)/[^\"'\\s>)]+",
                    "This copied or install-layout Bootstrap asset must be rebuilt from 5.3.6; do not patch generated bytes and verify deployment, license, source maps, and cache busting"));
    private static final List<BootstrapPlainTextSupport.Risk> STYLES = List.of(
            risk("@(?:import|use|forward)\\s+(['\"])(?:~)?bootstrap/(?:scss|dist)/[^'\"]+\\1",
                    "A custom Bootstrap Sass/CSS build crosses Dart Sass, partial layout, maps import order, functions, variables, color modes, utilities, and deprecations; rebuild and visually regress every theme"),
            risk("(?:theme-color-level|color-level|theme-color|gray|color|yiq|hover|hover-focus|plain-hover-focus|hover-focus-active|text-hide|retina-img|form-control-focus)\\s*\\(",
                    "This Bootstrap Sass function or mixin was renamed or removed; select a supported variable, color function, utility, or application mixin and test compiled output"),
            risk("\\$(?:enable-prefers-reduced-motion-media-query|enable-pointer-cursor-for-buttons|display-[1-4]-(?:size|weight)|embed-responsive-aspect-ratios|tooltip-margin|popover-arrow-(?:color|outer-color))\\b",
                    "This Bootstrap Sass variable was renamed, consolidated, or deprecated; migrate the custom theme against the 5.3.6 variable and map contract"),
            risk("\\.(?:custom-control|custom-select|custom-file|form-group|form-row|input-group-(?:append|prepend)|badge-pill|close|sr-only|embed-responsive|float-(?:left|right)|text-(?:left|right)|m[lr]-[0-5])(?:\\b|(?=[.:#\\s>+~\\[]))",
                    "This custom selector overrides a removed or renamed Bootstrap contract; migrate the selector deliberately and verify specificity, RTL, states, and visual snapshots"),
            risk("(?:vendor|node_modules)/bootstrap/(?:dist|js|scss)/[^\"'\\s>)]+",
                    "This copied Bootstrap source or asset binds to install layout; rebuild from 5.3.6 and verify theme compilation, deployment, source maps, and caching"));

    @Override
    public String getDisplayName() {
        return "Find Bootstrap 5 template and style migration risks";
    }

    @Override
    public String getDescription() {
        return "Marks structural forms/components, accessibility, Bootstrap 3 remnants, removed classes, negative margins, CDN/copied assets, and Sass/CSS contracts.";
    }

    @Override
    public TreeVisitor<?, ExecutionContext> getVisitor() {
        return new PlainTextVisitor<ExecutionContext>() {
            @Override
            public PlainText visitText(PlainText text, ExecutionContext ctx) {
                PlainText visited = super.visitText(text, ctx);
                if (BootstrapSupport.isMarkup(visited.getSourcePath())) {
                    return BootstrapPlainTextSupport.mark(visited, MARKUP, true);
                }
                if (BootstrapSupport.isStyle(visited.getSourcePath())) {
                    return BootstrapPlainTextSupport.mark(visited, STYLES, false);
                }
                return visited;
            }
        };
    }
}
